### ISSUE TITLE
Deleting users violates foreign key constraints

### ISSUE THREAD

**Issue by jjamay** [ProjectTwentyFive/task-sourcing#10]
#5 unable to delete users as it violates table constraints

**Comment by jarrett91** [comment]
I assume it's violating the FK constraints in bids and tasks? I guess we can setup a cascade delete

**Comment by justinhw** [comment]
SQLSTATE[23503]: Foreign key violation: 7 ERROR: update or delete on table "users" violates foreign key constraint "tasks_owner_foreign" on table "tasks"
DETAIL: Key (id)=(13001) is still referenced from table "tasks". (SQL: DELETE FROM users where id = 13001)

**Comment by justinhw** [comment]
@hooitong can you generate a new migration file with the necessary cascade so we can run it on our systems too?

Can you send us the newly generated SQL file too with the raw SQL?

**Comment by jarrett91** [comment]
You guys can directly edit the migration file and run `php artisan migrate:reset` to reflect changes in the database.

Take a look at https://laravel.com/docs/5.4/migrations#indexes and scroll down to the foreign key. I guess we can explicitly declare relationships in the migration file for consistency. 

For example in the migration table,
```
$table->foreign('user_id')
      ->references('id')->on('users')
      ->onDelete('cascade');
```

As for the raw SQL you can see it using DataGrip (https://www.jetbrains.com/datagrip/) under the DDL tab. However, I will generate accordingly and distribute when I have the time as well.
