### ISSUE TITLE
I can bid for my own task

### ISSUE THREAD

**Issue by justinhw** [ProjectTwentyFive/task-sourcing#37]

**Comment by JoshuaChing** [comment]
you need to check if they're logged in

@if (Auth::check() && ($user->is_admin || $user->id == $task->owner))

**Comment by justinhw** [comment]
if they're not online they can't see the page but sure we can add it

**Comment by JoshuaChing** [comment]
oh we should probably block people from viewing certain pages then (this ones still public)

**Comment by justinhw** [comment]
we can create another story for that ^ 

closing this issue with the updated check
