### ISSUE TITLE
[EPIC] REST Interface for Users

### ISSUE THREAD

**Issue by jjamay** [ProjectTwentyFive/task-sourcing#5]
We are currently using Laravels authentication. It would be nice if we could have our own login system even if it isn't secure.

TODO:
- [ ] register https://github.com/ProjectTwentyFive/task-sourcing/issues/9
- [ ] login
- [ ] logout

**Comment by jarrett91** [comment]
Changed assignee to @JustinSYDE since he is handling all the user.

**Comment by jarrett91** [comment]
@JustinSYDE the MethodNotAllowedHttpException you were getting from postman is because every route in the api is prefixed with 'api' e.g. DELETE "http://task.app/api/tasks/1".

 It should work if you disable the auth middleware for now.
