### ISSUE TITLE
Update readme so TAs can setup our project properly

### ISSUE THREAD

**Issue by justinhw** [ProjectTwentyFive/task-sourcing#63]

**Comment by JoshuaChing** [comment]
we should probably have a way for them to pre-populate the data
and then give them steps to navigate to different parts/functionalities of the project

**Comment by jarrett91** [comment]
Basic instructions to setup the application has been updated in 480baa04f58a1a06fb8f2e9e37c297888031bf97. Prepopulation is discussed in #60. The website should be intuitive enough and I highly doubt they actually play with our application outside the demonstration.
