### ISSUE TITLE
edit, delete button consistencies

### ISSUE THREAD

**Issue by JoshuaChing** [ProjectTwentyFive/task-sourcing#73]
You can't edit, delete a completed task on the individual task page and the dashboard.
You can edit, delete a completed task on the task list page.

We should decide on one or the other and implement it.

**Comment by jjamay** [comment]
I don't think it's necessary to have edit and delete buttons on the dashboard since you can just click on a task to edit and delete. It also gets messy with the redirects after editing/deleting.
