### ISSUE TITLE
Deployment to Server with Domain

### ISSUE THREAD

**Issue by jarrett91** [ProjectTwentyFive/task-sourcing#75]
Before presentation day I will deploy on my personal server and domain. This allows us to not only present in during our presentation but also allow the TA to possibly mark if he/she cannot run it on their machine.

After semester is over, I will take it down.

**Comment by jarrett91** [comment]
Will be completed on Saturday.

**Comment by hooitong** [comment]
Decided to use Heroku to serve instead. (Doesn't cost me any money)

**Comment by jarrett91** [comment]
Unfixed due to time constraints and lack of real importance
