### ISSUE TITLE
Advanced Queries

### ISSUE THREAD

**Issue by jjamay** [ProjectTwentyFive/task-sourcing#77]
Everyone should add 1 feature that makes use of at least 1 advanced query. Right now we are not using any complex queries at all.

- [x] Jordan
- [ ] Justin
- [x] Josh
- [x] Jarrett
- [ ] Nicholas

**Comment by jjamay** [comment]
- [ ] Jordan
- [ ] Justin
- [ ] Josh
- [ ] Jarrett

**Comment by jarrett91** [comment]
My advanced query will most probably be some form of sorting or view type for the tasks we have. Maybe pagination if I have time. Refer to #91

**Comment by jjamay** [comment]
cool!

**Comment by JoshuaChing** [comment]
Jordan's advance query for reference: https://github.com/ProjectTwentyFive/task-sourcing/pull/85

**Comment by JoshuaChing** [comment]
Advance query: find all users who have created a task for all the different common task categories https://github.com/ProjectTwentyFive/task-sourcing/pull/99

**Comment by jarrett91** [comment]
Sorry guys. Not enough time for the sort. If someone has time, he can take over.  It's a good feature to have.  Refer to #91 .

I will instead display some statistics about the application for the admin to view. (simpler but still use abit more complex queries). Refer to #105

**Comment by jarrett91** [comment]
Some statistics in #105

**Comment by JoshuaChing** [comment]
Advance query: find users with most completed tasks https://github.com/ProjectTwentyFive/task-sourcing/pull/107

**Comment by JoshuaChing** [comment]
Advance query: find users who has earned the most money from completed tasks https://github.com/ProjectTwentyFive/task-sourcing/pull/108
