### ISSUE TITLE
Accessing the url http://taskr.app

### ISSUE THREAD

**Issue by nchlsc** [ProjectTwentyFive/task-sourcing#78]
ErrorException in UrlGenerator.php line 304:
Route [tasks.show] not defined. (View: /home/vagrant/Code/task-sourcing-master/resources/views/home.blade.php)

trying to access http://taskr.app causes this error
accessing urls like taskr.app/tasks still works though

**Comment by JoshuaChing** [comment]
tested on my local machine, home page works fine for me

may be something specific to Nicholas' branch

going to close ticket
